
# Example configuration for model comparison
# You can use either the 'series' mapping form below or a top-level mapping.
series:
  baseline_yolo:
    name: "YOLOv8n-Baseline"
    type: baseline
    input:
      - /home/mpascual/research/results/mga/YOLOv8n_baseline/train_yolov8n_baseline/results.csv
    style:
      color: "#1f77b4"
      linestyle: "-"
      marker: "o"
      markersize: 2

  mga_model_gated:
    name: "MaskedECA - Gate"
    type: mga
    input:
      - /home/mpascual/research/results/mga/MGA_YOLO/masked_eca_yolov8n_withgate/results.csv
    style:
      color: "#d62728"
      linestyle: "-"
      marker: "s"
      markersize: 2


